"""add_attendance_tables

Revision ID: 804f7b514082
Revises: b2f1d3307f25
Create Date: 2026-06-29 11:15:17.276217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804f7b514082'
down_revision: Union[str, None] = 'b2f1d3307f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_roll_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.Enum('morning', 'afternoon', 'night', name='shift'), nullable=False),
    sa.Column('conducted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('conducted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conducted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'shift', name='uq_roll_call_date_shift')
    )
    op.create_index(op.f('ix_attendance_roll_calls_id'), 'attendance_roll_calls', ['id'], unique=False)
    op.create_table('attendance_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_call_id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('expected_status', sa.Enum('present', 'on_pass', 'external_appointment', 'hospitalized', 'absent_without_leave', 'discharged', name='presencestatus'), nullable=False),
    sa.Column('actual_status', sa.Enum('present', 'on_pass', 'external_appointment', 'hospitalized', 'absent_without_leave', 'discharged', name='presencestatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['roll_call_id'], ['attendance_roll_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_entries_id'), 'attendance_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_entries_id'), table_name='attendance_entries')
    op.drop_table('attendance_entries')
    op.drop_index(op.f('ix_attendance_roll_calls_id'), table_name='attendance_roll_calls')
    op.drop_table('attendance_roll_calls')
    # ### end Alembic commands ###
