"""add medication module tables

Revision ID: b2f1d3307f25
Revises: c8515fe2d626
Create Date: 2026-06-20 18:03:30.296107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2f1d3307f25'
down_revision: Union[str, None] = 'c8515fe2d626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('med_time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_med_time_slots_id'), 'med_time_slots', ['id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('strength', sa.String(), nullable=True),
    sa.Column('is_controlled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    op.create_table('resident_allergies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('substance', sa.String(), nullable=False),
    sa.Column('reaction', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('mild', 'moderate', 'severe', name='allergyseverity'), nullable=True),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resident_allergies_id'), 'resident_allergies', ['id'], unique=False)
    op.create_table('medication_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('dose', sa.String(), nullable=False),
    sa.Column('route', sa.Enum('oral', 'im', 'sc', 'other', name='medicationroute'), nullable=False),
    sa.Column('schedule_type', sa.Enum('scheduled', 'prn', name='scheduletype'), nullable=False),
    sa.Column('times', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('frequency_text', sa.String(), nullable=True),
    sa.Column('prn_reason', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('prescribed_by_external', sa.String(), nullable=True),
    sa.Column('prescriber_institution', sa.String(), nullable=True),
    sa.Column('transcribed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('receta_file_id', sa.Integer(), nullable=True),
    sa.Column('is_controlled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'finished', name='orderstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['receta_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['transcribed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_orders_id'), 'medication_orders', ['id'], unique=False)
    op.create_table('medication_administrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'taken', 'refused', 'omitted', name='administrationstatus'), nullable=False),
    sa.Column('administered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('administered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('witness_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['administered_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['medication_orders.id'], ),
    sa.ForeignKeyConstraint(['witness_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_administrations_id'), 'medication_administrations', ['id'], unique=False)

    # Seed franjas horarias por defecto
    op.bulk_insert(
        sa.table(
            'med_time_slots',
            sa.column('label', sa.String),
            sa.column('time', sa.Time),
            sa.column('sort_order', sa.Integer),
        ),
        [
            {'label': 'Mañana',   'time': '06:00:00', 'sort_order': 1},
            {'label': 'Mediodía', 'time': '12:00:00', 'sort_order': 2},
            {'label': 'Tarde',    'time': '18:00:00', 'sort_order': 3},
            {'label': 'Noche',    'time': '21:00:00', 'sort_order': 4},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_administrations_id'), table_name='medication_administrations')
    op.drop_table('medication_administrations')
    op.drop_index(op.f('ix_medication_orders_id'), table_name='medication_orders')
    op.drop_table('medication_orders')
    op.drop_index(op.f('ix_resident_allergies_id'), table_name='resident_allergies')
    op.drop_table('resident_allergies')
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_med_time_slots_id'), table_name='med_time_slots')
    op.drop_table('med_time_slots')
    sa.Enum(name='administrationstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='orderstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='scheduletype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='medicationroute').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='allergyseverity').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
