"""soft_delete_columns

Revision ID: c8515fe2d626
Revises: dca862fea910
Create Date: 2026-06-10 16:32:50.239432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8515fe2d626'
down_revision: Union[str, None] = 'dca862fea910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admissions', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('admissions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('consultations', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('consultations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('daily_logs', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('daily_logs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('residents', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('residents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('residents', 'deleted_at')
    op.drop_column('residents', 'is_deleted')
    op.drop_column('daily_logs', 'deleted_at')
    op.drop_column('daily_logs', 'is_deleted')
    op.drop_column('consultations', 'deleted_at')
    op.drop_column('consultations', 'is_deleted')
    op.drop_column('admissions', 'deleted_at')
    op.drop_column('admissions', 'is_deleted')
    # ### end Alembic commands ###
