"""create all tables

Revision ID: dca862fea910
Revises: f952e6d98f02
Create Date: 2026-06-06 15:50:00.235325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dca862fea910'
down_revision: Union[str, None] = 'f952e6d98f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_number', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.Enum('single', 'married', 'divorced', 'widowed', 'common_law', name='maritalstatus'), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('judicial_situation', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('education_level', sa.Enum('none', 'primary', 'secondary', 'technical', 'university', 'postgraduate', name='educationlevel'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relatives_id'), 'relatives', ['id'], unique=False)
    op.create_index(op.f('ix_relatives_id_number'), 'relatives', ['id_number'], unique=True)
    op.create_table('treatment_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_treatment_areas_id'), 'treatment_areas', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'counselor', 'medical', 'social_worker', 'psychologist', 'occupational_therapist', 'receptionist', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('operation_type', sa.Enum('create', 'update', 'delete', name='operationtype'), nullable=False),
    sa.Column('table_affected', sa.String(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('s3_bucket', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_table('professionals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['treatment_areas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professionals_id'), 'professionals', ['id'], unique=False)
    op.create_table('residents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('id_number', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', 'other', name='sex'), nullable=True),
    sa.Column('marital_status', sa.Enum('single', 'married', 'divorced', 'widowed', 'common_law', name='maritalstatus'), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('canton', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('address_other', sa.String(), nullable=True),
    sa.Column('phone_home', sa.String(), nullable=True),
    sa.Column('phone_mobile', sa.String(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(), nullable=True),
    sa.Column('is_insured', sa.Boolean(), nullable=True),
    sa.Column('insurance_type', sa.String(), nullable=True),
    sa.Column('photo_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['photo_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_residents_code'), 'residents', ['code'], unique=True)
    op.create_index(op.f('ix_residents_id'), 'residents', ['id'], unique=False)
    op.create_index(op.f('ix_residents_id_number'), 'residents', ['id_number'], unique=True)
    op.create_table('admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('admission_type', sa.Enum('first', 'readmission', name='admissiontype'), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('discharge_reason', sa.String(), nullable=True),
    sa.Column('assigned_counselor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('intake_pending', 'consents_pending', 'assessment_in_progress', 'treatment_active', 'discharged', 'abandoned', name='admissionstatus'), nullable=False),
    sa.Column('referral_source', sa.String(), nullable=True),
    sa.Column('admission_condition', sa.Text(), nullable=True),
    sa.Column('initial_diagnosis', sa.Text(), nullable=True),
    sa.Column('sponsor_name', sa.String(), nullable=True),
    sa.Column('sponsor_relationship', sa.String(), nullable=True),
    sa.Column('sponsor_phone', sa.String(), nullable=True),
    sa.Column('sponsor_address', sa.Text(), nullable=True),
    sa.Column('judicial_status', sa.String(), nullable=True),
    sa.Column('has_support_network', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_counselor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admissions_admission_number'), 'admissions', ['admission_number'], unique=True)
    op.create_index(op.f('ix_admissions_id'), 'admissions', ['id'], unique=False)
    op.create_table('education_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('academic_grade', sa.String(), nullable=True),
    sa.Column('year_attended', sa.Integer(), nullable=True),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_records_id'), 'education_records', ['id'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_members_id'), 'family_members', ['id'], unique=False)
    op.create_table('patient_relatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('relative_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['relative_id'], ['relatives.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_relatives_id'), 'patient_relatives', ['id'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.Enum('internment_service', 'internment', 'search', 'drug_test', 'cctv', 'info_release', 'weapons', 'iafa_actions', 'individual_approach', 'referral', 'record_access', 'rights_focus', 'labor', 'non_discrimination', 'sponsor', 'manual', 'labor_provision', name='consenttype'), nullable=False),
    sa.Column('is_signed', sa.Boolean(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('authorized_persons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_id'), 'consent_records', ['id'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('consultation_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('next_appointment_date', sa.Date(), nullable=True),
    sa.Column('consultation_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['area_id'], ['treatment_areas.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_id'), 'consultations', ['id'], unique=False)
    op.create_table('consumption_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('age_first_use', sa.Integer(), nullable=True),
    sa.Column('primary_drug', sa.String(), nullable=True),
    sa.Column('drug_use_frequency', sa.String(), nullable=True),
    sa.Column('other_drugs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('previous_internments_count', sa.Integer(), nullable=True),
    sa.Column('previous_internment_places', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('worst_experience', sa.Text(), nullable=True),
    sa.Column('history_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_id')
    )
    op.create_index(op.f('ix_consumption_snapshots_id'), 'consumption_snapshots', ['id'], unique=False)
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('logged_by_id', sa.Integer(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('intervention_type', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['logged_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_logs_id'), 'daily_logs', ['id'], unique=False)
    op.create_table('economic_situations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('has_worked', sa.Boolean(), nullable=True),
    sa.Column('current_job', sa.String(), nullable=True),
    sa.Column('work_phone', sa.String(), nullable=True),
    sa.Column('workplace', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('monthly_income_colones', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('house_type', sa.String(), nullable=True),
    sa.Column('rent_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('family_income_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('financial_assistance_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_id')
    )
    op.create_index(op.f('ix_economic_situations_id'), 'economic_situations', ['id'], unique=False)
    op.create_table('exit_passes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('departure_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_date_expected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_date_actual', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('companion', sa.String(), nullable=True),
    sa.Column('pass_type', sa.Enum('regular', 'special', name='passtype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'completed', name='passstatus'), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_passes_id'), 'exit_passes', ['id'], unique=False)
    op.create_table('family_therapy_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('attendees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_therapy_sessions_id'), 'family_therapy_sessions', ['id'], unique=False)
    op.create_table('household_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_members_id'), 'household_members', ['id'], unique=False)
    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('social_security_validated', sa.Boolean(), nullable=True),
    sa.Column('iafa_icd_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completion_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_id')
    )
    op.create_index(op.f('ix_medical_records_id'), 'medical_records', ['id'], unique=False)
    op.create_table('occupational_therapy_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=True),
    sa.Column('assessment_date', sa.Date(), nullable=True),
    sa.Column('initial_diagnostic_impression', sa.Text(), nullable=True),
    sa.Column('occupational_profile', sa.Text(), nullable=True),
    sa.Column('completion_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_id')
    )
    op.create_index(op.f('ix_occupational_therapy_assessments_id'), 'occupational_therapy_assessments', ['id'], unique=False)
    op.create_table('personal_items_inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_signature_file_id', sa.Integer(), nullable=True),
    sa.Column('staff_signature_file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_signature_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['user_signature_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_id')
    )
    op.create_index(op.f('ix_personal_items_inventories_id'), 'personal_items_inventories', ['id'], unique=False)
    op.create_table('program_abandonments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('abandoned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('staff_notified_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['staff_notified_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_id')
    )
    op.create_index(op.f('ix_program_abandonments_id'), 'program_abandonments', ['id'], unique=False)
    op.create_table('psychology_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('psychologist_id', sa.Integer(), nullable=True),
    sa.Column('assessment_date', sa.Date(), nullable=True),
    sa.Column('initial_diagnostic_impression', sa.Text(), nullable=True),
    sa.Column('observable_assessment', sa.Text(), nullable=True),
    sa.Column('diagnostic_tests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completion_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['psychologist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_id')
    )
    op.create_index(op.f('ix_psychology_assessments_id'), 'psychology_assessments', ['id'], unique=False)
    op.create_table('social_work_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('social_worker_id', sa.Integer(), nullable=True),
    sa.Column('assessment_date', sa.Date(), nullable=True),
    sa.Column('diagnostic_impression', sa.Text(), nullable=True),
    sa.Column('initial_assessment', sa.Text(), nullable=True),
    sa.Column('completion_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['social_worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_id')
    )
    op.create_index(op.f('ix_social_work_assessments_id'), 'social_work_assessments', ['id'], unique=False)
    op.create_table('therapeutic_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('assessor_id', sa.Integer(), nullable=True),
    sa.Column('assessment_date', sa.Date(), nullable=True),
    sa.Column('initial_summary', sa.Text(), nullable=True),
    sa.Column('clinical_history_summary', sa.Text(), nullable=True),
    sa.Column('europal_si_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('socrates_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('urica_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('afc_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relapse_prevention_interview', sa.Text(), nullable=True),
    sa.Column('relapse_prevention_plan', sa.Text(), nullable=True),
    sa.Column('completion_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['assessor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_id')
    )
    op.create_index(op.f('ix_therapeutic_assessments_id'), 'therapeutic_assessments', ['id'], unique=False)
    op.create_table('treatment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('plan_details', sa.Text(), nullable=True),
    sa.Column('life_project', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_id')
    )
    op.create_index(op.f('ix_treatment_plans_id'), 'treatment_plans', ['id'], unique=False)
    op.create_table('drug_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_record_id', sa.Integer(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_tests_id'), 'drug_tests', ['id'], unique=False)
    op.create_table('medication_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_record_id', sa.Integer(), nullable=False),
    sa.Column('treatment_type', sa.String(), nullable=True),
    sa.Column('medication_name', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('prescribed_by', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_logs_id'), 'medication_logs', ['id'], unique=False)
    op.create_table('treatment_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treatment_plan_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.Enum('orientation', 'adaptation', 'development', 'consolidation', 'reintegration', name='stagename'), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('progress_notes', sa.Text(), nullable=True),
    sa.Column('extension_consent_signed', sa.Boolean(), nullable=True),
    sa.Column('advancement_criteria', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'completed', 'extended', name='stagestatus'), nullable=False),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_stages_id'), 'treatment_stages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treatment_stages_id'), table_name='treatment_stages')
    op.drop_table('treatment_stages')
    op.drop_index(op.f('ix_medication_logs_id'), table_name='medication_logs')
    op.drop_table('medication_logs')
    op.drop_index(op.f('ix_drug_tests_id'), table_name='drug_tests')
    op.drop_table('drug_tests')
    op.drop_index(op.f('ix_treatment_plans_id'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_index(op.f('ix_therapeutic_assessments_id'), table_name='therapeutic_assessments')
    op.drop_table('therapeutic_assessments')
    op.drop_index(op.f('ix_social_work_assessments_id'), table_name='social_work_assessments')
    op.drop_table('social_work_assessments')
    op.drop_index(op.f('ix_psychology_assessments_id'), table_name='psychology_assessments')
    op.drop_table('psychology_assessments')
    op.drop_index(op.f('ix_program_abandonments_id'), table_name='program_abandonments')
    op.drop_table('program_abandonments')
    op.drop_index(op.f('ix_personal_items_inventories_id'), table_name='personal_items_inventories')
    op.drop_table('personal_items_inventories')
    op.drop_index(op.f('ix_occupational_therapy_assessments_id'), table_name='occupational_therapy_assessments')
    op.drop_table('occupational_therapy_assessments')
    op.drop_index(op.f('ix_medical_records_id'), table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_household_members_id'), table_name='household_members')
    op.drop_table('household_members')
    op.drop_index(op.f('ix_family_therapy_sessions_id'), table_name='family_therapy_sessions')
    op.drop_table('family_therapy_sessions')
    op.drop_index(op.f('ix_exit_passes_id'), table_name='exit_passes')
    op.drop_table('exit_passes')
    op.drop_index(op.f('ix_economic_situations_id'), table_name='economic_situations')
    op.drop_table('economic_situations')
    op.drop_index(op.f('ix_daily_logs_id'), table_name='daily_logs')
    op.drop_table('daily_logs')
    op.drop_index(op.f('ix_consumption_snapshots_id'), table_name='consumption_snapshots')
    op.drop_table('consumption_snapshots')
    op.drop_index(op.f('ix_consultations_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_consent_records_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_patient_relatives_id'), table_name='patient_relatives')
    op.drop_table('patient_relatives')
    op.drop_index(op.f('ix_family_members_id'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_education_records_id'), table_name='education_records')
    op.drop_table('education_records')
    op.drop_index(op.f('ix_admissions_id'), table_name='admissions')
    op.drop_index(op.f('ix_admissions_admission_number'), table_name='admissions')
    op.drop_table('admissions')
    op.drop_index(op.f('ix_residents_id_number'), table_name='residents')
    op.drop_index(op.f('ix_residents_id'), table_name='residents')
    op.drop_index(op.f('ix_residents_code'), table_name='residents')
    op.drop_table('residents')
    op.drop_index(op.f('ix_professionals_id'), table_name='professionals')
    op.drop_table('professionals')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_treatment_areas_id'), table_name='treatment_areas')
    op.drop_table('treatment_areas')
    op.drop_index(op.f('ix_relatives_id_number'), table_name='relatives')
    op.drop_index(op.f('ix_relatives_id'), table_name='relatives')
    op.drop_table('relatives')
    # ### end Alembic commands ###
